name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Swagger Codegen
        uses: bjerkio/swagger-codegen-action@v1
        with:
          args: |
            generate -l openapi-yaml -i lb.yaml -o single-file
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: single-file/openapi.yaml
          # spec-url: https://raw.githubusercontent.com/rain0r/listenbrainz-openapi/refs/heads/master/lb.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
