name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Generate a single YAML-file
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: openapi-yaml
          openapi-file: lb.yaml
      - name: Generate Swagger UI from a single YAML-file
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: openapi-yaml-client/openapi/openapi.yaml          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
